"""empty message

Revision ID: 17c2cbb7a158
Revises: bfa94e255412
Create Date: 2020-08-12 21:46:14.324364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c2cbb7a158'
down_revision = 'bfa94e255412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('gener', sa.String(length=120), nullable=True))
    op.drop_column('venues', 'geners')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('geners', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venues', 'gener')
    # ### end Alembic commands ###
