"""empty message

Revision ID: 2504e1b85fd0
Revises: 3249f734ed2e
Create Date: 2020-08-19 09:15:17.406033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2504e1b85fd0'
down_revision = '3249f734ed2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artists', 'venues', ['venue_id'], ['id'])
    op.add_column('venues', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venues', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'artist_id')
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_column('artists', 'venue_id')
    # ### end Alembic commands ###
