"""empty message

Revision ID: 7a50fd6e0e65
Revises: 17c2cbb7a158
Create Date: 2020-08-12 21:55:55.346183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a50fd6e0e65'
down_revision = '17c2cbb7a158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    op.drop_column('venues', 'gener')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('gener', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
