"""empty message

Revision ID: e29ce0c9625b
Revises: e92595b1e1c5
Create Date: 2020-08-14 14:53:36.744583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29ce0c9625b'
down_revision = 'e92595b1e1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('shows_vuenue_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'])
    op.drop_column('shows', 'vuenue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('vuenue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_vuenue_id_fkey', 'shows', 'venues', ['vuenue_id'], ['id'])
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
